### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by suzu12** [suzu12/furima-31669#30]
### ■フリマアプリのURL
[こちらから挙動確認よろしくお願いいたします！](https://furima-31669.herokuapp.com/)

#### ■Basic認証のIDとパスワード
ID | admin
-- | --
パスワード | 2222

#### ■出品者用のメールアドレスとパスワード
メールアドレス | test1@co.jp
------------- | ---------------
パスワード | test123

#### ■購入者用のメールアドレスとパスワード
メールアドレス | kounyu123@hogehoge.com
-- | --
パスワード | kounyu123

#### ■購入用カードの番号・期限・セキュリティコード( PAY.JPテストカード情報 )

カード番号  | 4242424242424242（16桁）
-- | --
CVC            | 123
有効期限     | 登録時より未来

**Comment by tech-taro** [comment]
suzu12さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
ユーザー管理機能の確認
・新規登録/ユーザー情報（ユーザー本名は、全角（漢字・ひらがな・カタカナ）での入力が必須であること）
→こちらですが漢字入力しかできないようになっているので、修正をお願い致します。

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by suzu12** [comment]
@tech-taro さん。
コードレビューありがとうございます。

修正いたしました！！
お手数おかけいたしますがご確認よろしくお願いいたします！

**Comment by tech-taro** [comment]
suzu12さん、学習お疲れ様です。

大変申し訳ございません。
先ほどは私が誤った連絡をしてしまい、ProtoSpaceの提出フォームのリンクを送信しておりました

お手数おかけし大変申し訳ないのですが、下記フォームより再度提出をお願い致します。
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by suzu12** [comment]
@tech-taro さん。
ご返信ありがとうございます！

再提出いたしましたので、ご確認よろしくお願いいたします！

**Comment by tcamp1234** [comment]
suzu12、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

大変素晴らしくできていたので、一点だけ任意修正点を記載致します。
・ユーザー登録時のエラーハンドリングも日本語にすることができるとより親切な設計になるかと思いました。
<img width="704" alt="スクリーンショット 2020-11-09 11 08 39" src="https://user-images.githubusercontent.com/64445215/98492989-c2895000-227c-11eb-89f4-70c7989693f2.png">


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by suzu12** [comment]
@tcamp1234 さん。
挙動確認していただきありがとうございます！

ご指摘いただきありがとうございます。
デバイスの日本語対応もしたほうが、エラー時わかりやすいですね！
すぐに修正いたします。

今後ともよろしくお願いいたします。
